### ISSUE TITLE
Positions/Transforms are incorrect

### ISSUE THREAD

**Issue by atteneder** [toshiks/glTF-qucklook#3]
First of all thanks a bunch for this plug-in! great idea!

I tested some items from the official glTF samle library and It seems like the transforms of primitives/nodes are not correct. Example, the [buggy scene](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF):

<img width="918" alt="grafik" src="https://user-images.githubusercontent.com/2593014/64927043-f1856c80-d805-11e9-95f5-cff057411ec3.png">

**Comment by toshiks** [comment]
Hello! Thank you for your attention for this project. I fixed that bug. Now it works well :) 
I update latest release with this fix!

**Comment by atteneder** [comment]
Great to hear!
GitHub quick tip:
If you mention the fixed issue in the commit message, GitHub will reference them and can also close it automatically. In this example you could add `fixes #3` to the message. See here:
<https://help.github.com/en/articles/closing-issues-using-keywords>
Thanks!
